### ISSUE TITLE
Cursor Goes Beyond in Text Input in IE10

### ISSUE THREAD

**Issue by iosulfur** [cloudfour/hideShowPassword#19]
This stack overflow (no valid anser at the time of my re-posting here) explaisn the problem well:
http://stackoverflow.com/questions/25402513/cursor-goes-beyond-in-text-input-in-ie10

This plugin sets `padding-right` on the input. Then the above issue occurs on IE10 with long passwords.

**Comment by tylersticka** [comment]
Hi @iosulfur,

Sorry to hear you're encountering this issue.

The goal of the `innerToggle` functionality is to have an _inset_ password visibility toggle with a great touchscreen experience. An unfortunate side effect of this is that the options for changing its relationship to the `<input>` element are somewhat rigid. Because of this (and the relatively low usability impact and audience for this particular bug), there is a low likelihood we'll be able to address this specific issue for users of IE10 without making the experience worse for everyone else (though we welcome pull requests from folks who are smarter than us when it comes to solving these sorts of problems).

If this issue is a show-stopper for you, I have two recommendations you might consider...

### Disabling the functionality for IE10+

Microsoft actually ships their own password visibility toggle in IE10 and up if you're using Windows 8. As long as you are not hiding their controls ([see here](https://github.com/cloudfour/hideShowPassword#competing-controls-in-ie10-windows-8)), you could use the `enable` [option](https://github.com/cloudfour/hideShowPassword#options) to _only_ activate the plugin for other browsers:

```javascript
$('#example').hideShowPassword({
  enable: ! isIE // Just an example, insert your own browser detection logic
});
```

Obviously browser detection is not ideal, but since there's no way to feature detect for the password toggle, I can't see any other way to pull this technique off.

### Roll your own solution

The `innerToggle` is neat, but you don't _need_ it to use the plugin. You can markup and style your own toggle and controls. See [the third example in the demo](https://github.com/cloudfour/hideShowPassword/blob/master/index.html#L95-L100).

**Comment by iosulfur** [comment]
Thank you. Disabling it for IE10, and allowing their browser implementation
to persist is a feasible solution. I like the plugin, and continue to use
it. IE10's behavior is acceptable given the application's market, but I
will offer the disabling option to the designer.

Great plugin. Thanks for the bower support.

**Comment by tylersticka** [comment]
Thanks, @iosulfur !
