### ISSUE TITLE
Auto left and right margins not inherited in Firefox

### ISSUE THREAD

**Issue by raddevon** [cloudfour/hideShowPassword#33]
I have an element with auto left and right margins. In Chrome and other Webkit-based browsers, this is inherited by the wrapper by assigning the margin the calculated pixel value of the left and right margins. In Firefox, the left and right margins are instead inherited as 0px margins.

**Comment by tylersticka** [comment]
Unfortunately, this one comes down to inconsistencies in the return value of `window.getComputedStyle` in Firefox: http://stackoverflow.com/a/24292611

Ideally, this would be fixed by styling `hideShowPassword-wrapper` (or whatever class name you choose), changing the `inheritStyles` array (which there's an open issue for, see #34), or moving the offending styles to a containing element.
