### ISSUE TITLE
Disable added inline styles

### ISSUE THREAD

**Issue by markphd** [cloudfour/hideShowPassword#55]
How do I remove the inline styles on `hideShowPassword-wrapper` and `hideShowPassword-field`?

I tried adding the style property in the options object, but still the inline styles are added automatically.

**Comment by tylersticka** [comment]
You can't currently get rid of all inline styles, but you can get rid of most of them by overriding a pile of options:

```javascript
$('input').hideShowPassword({
  innerToggle: true,
  toggle: {
    styles: {
      position: '' // Removes position style
    },
    verticalAlign: 'top', // Removes negative margin styles
    offset: '' // Removes top style
  },
  wrapper: {
    enforceWidth: false, // Removes width style
    styles: {
      position: '' // Removes position style
    },
    inheritStyles: [], // Removes styles inherited from input
    innerElementStyles: { // Removes styles applied to input
      marginTop: '',
      marginRight: '',
      marginBottom: '',
      marginLeft: ''
    }
  }
});
```

At the time this plugin was written, package managers like `npm` were not in fashion and it was typically cumbersome to include both CSS and JavaScript assets from a package, which is why it applies so many customization via inline styles. If I were to rewrite this today, I'd simplify things by moving as much of the style logic as possible into an accompanying stylesheet (#35) or re-evaluating which parts are still necessary (#46). 

My advice if you have very specific needs that break dramatically from the default inner toggle appearance is to _not_ use the `innerToggle` functionality, and instead just use [the basic methods](https://github.com/cloudfour/hideShowPassword#usage) to roll your own toggle.

**Comment by markphd** [comment]
@tylersticka thanks! I will work on my own toggle instead. Although I think it would be nice to pass an option in `innerToggle` to disable all styles.

```javascript
innerToggle: {
  enable: true,
  style: (default || none)
}
```
